
# Day 5 - Hairpin

```{r}
top <- c(8,1,9)
mid <- c(6,2,7)
bot <- c(5,4,3)
```

```{r}
# read in points per team
day5_raw <- read_csv('data/daav_cup_results - Day5.csv') 
  
day5_results <- map_dfr(1:nteams, ~getResults(day5_raw, .x, npools)) %>%
  cutNames()
  
day5_summary <- getSummary(day5_results) 

standings5 <- getStandings(day5_summary, standings4)

mvp <- getMVP(mvp, day5_results)

positions <- getPositions(day5_results)
```

Column {data-width=250}
--------------
### Top Bracket
```{r}
indivResults(cars_df$day5_top, positions, top)
```
Column {data-width=250}
--------------
### Middle Bracket
```{r}
indivResults(cars_df$day5_mid, positions, mid)
```
Column {data-width=250}
--------------
### Bottom Bracket
```{r}
indivResults(cars_df$day5_bot, positions, bot)
```

# Standings

Column {data-width=125}
--------------
### Day 5 Results
```{r}
dailyResults(day5_summary)
```
Column {data-width=125}
--------------
### Overall Standings
```{r}
dailyResults(standings5)
```
Column {data-width=125}
--------------
### MVP Standings
```{r}
dailyResults(mvp)
```





# Tournament Summary

Column {data-width=300} 
---------------------

### Tournament Winners
```{r}
# mvp table 
knitr::kable(standings5, align = c("r", "l","l")) %>%
  kable_styling(bootstrap_options = c("striped", "condensed"), 
                full_width = T) %>%
  row_spec(1,background = 'gold') %>%
  column_spec(2, width='4cm',bold = TRUE, color = "white", background = "red3") 
```

### MVP Winners
```{r}
# mvp table 
knitr::kable(mvp, align = c("r", "l","l")) %>%
  kable_styling(bootstrap_options = c("striped", "condensed"), 
                full_width = T) %>%
  row_spec(1,background = 'gold') %>%
  column_spec(2, width='4cm',bold = TRUE, color = "white", background = "red3") 
```



Column {data-width=600} 
---------------------
### Team Standings by Day
```{r}
# combine results tables for daily results

daily_results <- rbind(standings1,
                       standings2,
                       standings3,
                       standings4,
                       standings5) %>%
  mutate(Rank=factor(rep(1:5,each=nteams),levels=1:5)) %>%
  rename(Day=Rank)

# plot daily
ggplotly(
  ggplot(daily_results, aes(Day,Points,fill=Team)) +
    geom_col(position = 'dodge',colour='black') +
    geom_vline(xintercept = seq(1.5,5.5)) +
    scale_fill_manual(values = c('lightgreen','orange','magenta','gold','skyblue','red3'))+
    theme_minimal() +
    labs(title='Team Standings by Day',y='Cumulative Points'),
  tooltip = c('fill','y')
  )

```

### Pool MVPs
```{r}
# combine results tables for pool results
pool_mvp <- mvp %>%
  left_join(select(day1_results,Player,Team),by='Player') %>%
  left_join(select(data,Player=Name,Pool=Bracket),by='Player') 

# plot pools
ggplotly(
  ggplot(pool_mvp, aes(Team,Points,fill=Team,extra=Player)) +
    geom_bar(position = 'dodge',stat='identity',colour='black') +
    scale_fill_manual(values = c('lightgreen','orange','magenta','gold','skyblue','red3')) +
    facet_wrap(vars(Pool),nrow=2) +
    theme_minimal() +
    labs(title='Pool MVPs',y='Total Points',x='Pools') +
    theme(axis.text.x = element_blank()),
  tooltip='extra'
)
```
